version: 2.1
orbs:
  sk: wob-adarga/secret-key-orb@1.0.0
  snyk: snyk/snyk@0.1.0

executors:
  default:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/btrace-baader/kafka-topic-operator

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: Run Golang tests
          command: make test
      - snyk/scan:
          project: '${CIRCLE_PROJECT_REPONAME}'
          additional-arguments: "--remote-repo-url=https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
          fail-on-issues: true
          monitor-on-build: true
          severity-threshold: high
          organization: adarga

  build:
    executor: default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install -i ~/.local/aws-cli -b ~/.local/bin
      - run:
          name: Login to ECR
          command: aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
      - run:
          name: Docker Build commit tag
          command: BUILD_VERSION=${CIRCLE_TAG:=$CIRCLE_BRANCH+$CIRCLE_SHA1} IMG=$AWS_ECR_ACCOUNT_URL/adarga/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 make docker-build
      - snyk/scan:
          project: '${CIRCLE_PROJECT_REPONAME}'
          docker-image-name: '$AWS_ECR_ACCOUNT_URL/adarga/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1'
          target-file: Dockerfile
          fail-on-issues: true
          monitor-on-build: true
          severity-threshold: high
          organization: adarga
      - run:
          name: Docker Push commit tag
          command: IMG=$AWS_ECR_ACCOUNT_URL/adarga/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 make docker-push

  tag_promote:
    executor: default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install -i ~/.local/aws-cli -b ~/.local/bin
      - run:
          name: Login to ECR
          command: aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
      - run:
          name: Docker Pull commit tag
          command: docker pull $AWS_ECR_ACCOUNT_URL/adarga/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
      - run:
          name: Docker Tag release
          command: docker tag $AWS_ECR_ACCOUNT_URL/adarga/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $AWS_ECR_ACCOUNT_URL/adarga/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:=$CIRCLE_BRANCH}
      - run:
          name: Docker Push release
          command: docker push $AWS_ECR_ACCOUNT_URL/adarga/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG

workflows:
  version: 2
  test_build_scan_push:
    jobs:
      - test:
          context:
            - adarga-global
      - build:
          context:
            - adarga-global
            - adarga-operations-ecr
      - tag_promote:
          context:
            - adarga-operations-ecr
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only: main
