apiVersion: kafka.btrace.com/v1alpha1
kind: KafkaTopic
metadata:
  name: delete-me-1
  namespace: test
spec:
  partitions: 1
  replicationFactor: 3
  clusterRef:
    name: test-connection-1
    namespace: test
  config:
    "cleanup.policy": "compact"
    "min.compaction.lag.ms": "86400000"
    "max.compaction.lag.ms": "432000000"